name: Pack And Publish 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Configure nuget source
      run: dotnet nuget add source --username lucasoppc --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Push package
      run: dotnet nuget push "NetCore.Cryptography/bin/Release/lucasoppc.NetCore.Cryptography.1.0.0.nupkg" --source "github"
